#!/usr/bin/env python3
"""Mirror runtime spec files from skills/canopy-runtime/references/ into docs/reference/.

Canonical source: skills/canopy-runtime/references/ops.md (index) + ops/<slice>.md (per-feature
                  slices) + runtime-claude.md + runtime-copilot.md
                  (these are loaded by canopy-runtime at execution time)
Generated docs:   docs/reference/PRIMITIVES.md, docs/reference/RUNTIMES.md
                  (rendered by Jekyll into the public docs site)

Run from repo root:
    python scripts/sync-runtime-docs.py        # write the docs/reference/ files
    python scripts/sync-runtime-docs.py --check  # exit non-zero if generated content
                                                  differs from what's on disk

CI invokes the --check form to fail builds when the runtime files have changed
without the mirror being regenerated.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from textwrap import dedent


def demote_headings(text: str, levels: int = 1) -> str:
    """Increase every ATX heading by `levels`: # → ##, ## → ###, etc.

    Used when mirroring a runtime spec file as a section of a larger page —
    we want the page's intro to own the H1 and the mirrored sections to be
    H2s/H3s under it, not separate H1s.
    """
    pattern = re.compile(r"^(#{1,5}) ", re.MULTILINE)
    return pattern.sub(lambda m: "#" * (len(m.group(1)) + levels) + " ", text)

REPO = Path(__file__).resolve().parent.parent
SRC = REPO / "skills" / "canopy-runtime" / "references"
DST = REPO / "docs" / "reference"

GENERATED_BANNER = dedent(
    """\
    > **Auto-generated mirror.** Canonical source: [`{src_rel}`](https://github.com/kostiantyn-matsebora/claude-canopy/blob/master/{src_rel}). Edits go to the canonical file; this page is regenerated by `scripts/sync-runtime-docs.py`.
    """
)


# Order in which slices are concatenated into PRIMITIVES.md. Mirrors how a
# reader would learn the framework — core flow first, then interaction,
# control flow, parallelism, subagent dispatch, explore (legacy), verify.
PRIMITIVE_SLICE_ORDER = [
    "core",
    "interaction",
    "control-flow",
    "parallel",
    "subagent",
    "explore",
    "verify",
]


def render_primitives() -> str:
    """Build docs/reference/PRIMITIVES.md from the index + per-feature slices.

    Each slice's H1 is demoted to H2 so the page has a single H1 ("Framework
    Primitives") with each slice as a section underneath.
    """
    index_src = (SRC / "ops.md").read_text(encoding="utf-8")
    banner = (
        "> **Auto-generated mirror.** Canonical sources: "
        "[`skills/canopy-runtime/references/ops.md`](https://github.com/kostiantyn-matsebora/claude-canopy/blob/master/skills/canopy-runtime/references/ops.md)"
        " (index) and the per-feature slice files under "
        "[`skills/canopy-runtime/references/ops/`](https://github.com/kostiantyn-matsebora/claude-canopy/tree/master/skills/canopy-runtime/references/ops). "
        "Edits go to the canonical files; this page is regenerated by `scripts/sync-runtime-docs.py`.\n"
    )
    frontmatter = dedent(
        """\
        ---
        title: Primitives
        description: "Framework primitives — sliced by feature group. Mirrored from canopy-runtime."
        permalink: /reference/primitives/
        ---

        """
    )

    parts = [frontmatter, banner, "\n", demote_headings(index_src), "\n---\n\n"]
    for slice_name in PRIMITIVE_SLICE_ORDER:
        slice_path = SRC / "ops" / f"{slice_name}.md"
        if not slice_path.exists():
            raise FileNotFoundError(f"Expected primitive slice not found: {slice_path}")
        parts.append(demote_headings(slice_path.read_text(encoding="utf-8")))
        parts.append("\n---\n\n")
    # Trim the trailing separator
    if parts[-1] == "\n---\n\n":
        parts.pop()
    return "".join(parts)


def render_runtimes() -> str:
    """Build docs/reference/RUNTIMES.md from runtime-claude.md + runtime-copilot.md.

    The two source files each have their own H1 — they're standalone docs.
    On the combined page, demote both by one level so the page has a single
    H1 ("Runtime Specs") with each platform as an H2 underneath. This keeps
    the page TOC clean (no duplicated "Base Paths" entries).
    """
    claude_src = demote_headings((SRC / "runtime-claude.md").read_text(encoding="utf-8"))
    copilot_src = demote_headings((SRC / "runtime-copilot.md").read_text(encoding="utf-8"))
    banner = (
        "> **Auto-generated mirror.** Canonical sources: "
        "[`skills/canopy-runtime/references/runtime-claude.md`](https://github.com/kostiantyn-matsebora/claude-canopy/blob/master/skills/canopy-runtime/references/runtime-claude.md)"
        " and "
        "[`skills/canopy-runtime/references/runtime-copilot.md`](https://github.com/kostiantyn-matsebora/claude-canopy/blob/master/skills/canopy-runtime/references/runtime-copilot.md)"
        ". Edits go to the canonical files; this page is regenerated by `scripts/sync-runtime-docs.py`.\n"
    )
    frontmatter = dedent(
        """\
        ---
        title: Runtimes
        description: "Per-platform execution rules — Claude Code (native subagents) and GitHub Copilot (inline fallback). Mirrored from canopy-runtime."
        permalink: /reference/runtimes/
        ---

        """
    )
    intro = dedent(
        """\
        # Runtime Specs

        Canopy uses an interpreter pattern: the same `SKILL.md` runs on Claude Code and GitHub Copilot — only the runtime-spec file loaded at execution time differs. The two specs below are loaded by `canopy-runtime` based on the active host.

        ---

        """
    )
    return frontmatter + banner + "\n" + intro + claude_src + "\n---\n\n" + copilot_src


TARGETS = {
    DST / "PRIMITIVES.md": render_primitives,
    DST / "RUNTIMES.md": render_runtimes,
}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if generated content differs from on-disk files (CI mode).",
    )
    args = parser.parse_args()

    drift: list[Path] = []
    for path, render in TARGETS.items():
        expected = render()
        if args.check:
            if not path.exists():
                drift.append(path)
                print(f"MISSING  {path.relative_to(REPO)}", file=sys.stderr)
                continue
            # Universal-newlines mode normalizes CRLF (Windows working tree
            # with autocrlf=true) and LF (Linux/CI) to \n on read. The
            # `expected` string also uses \n, so the comparison is
            # platform-independent.
            actual = path.read_text(encoding="utf-8")
            if actual != expected:
                drift.append(path)
                print(f"DRIFT    {path.relative_to(REPO)}", file=sys.stderr)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            # Force LF on write so the file we commit is pure LF regardless
            # of host OS. Git's autocrlf may re-convert in the working tree
            # on Windows checkouts, but the in-repo bytes stay LF.
            path.write_bytes(expected.encode("utf-8"))
            print(f"WROTE    {path.relative_to(REPO)}")

    if args.check and drift:
        print(
            "\nRun `python scripts/sync-runtime-docs.py` to regenerate the mirror, "
            "then commit the result.",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
